In [44]:
df = pd.read_csv("/content/student_performance_dataset.csv")

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [46]:

print(df.head())

  Student_ID  Gender  Study_Hours_per_Week  Attendance_Rate  Past_Exam_Scores  \
0       S147    Male                    31        68.267841                86
1       S136    Male                    16        78.222927                73
2       S209  Female                    21        87.525096                74
3       S458  Female                    27        92.076483                99
4       S078  Female                    37        98.655517                63

  Parental_Education_Level Internet_Access_at_Home Extracurricular_Activities  \
0              High School                     Yes                        Yes
1                      PhD                      No                         No
2                      PhD                     Yes                         No
3                Bachelors                      No                         No
4                  Masters                      No                        Yes

   Final_Exam_Score Pass_Fail
0                63      Pass
1                50      Fail
2                55      Fail
3                65      Pass
4                70      Pass

In [47]:
df.describe()

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Final_Exam_Score
count,708.000000,708.000000,708.000000,708.000000
mean,26.132768,78.107722,77.871469,58.771186
std,8.877727,13.802802,14.402739,6.705877
min,10.000000,50.116970,50.000000,50.000000
25%,19.000000,67.550094,65.000000,52.000000
50%,27.000000,79.363046,79.000000,59.500000
75%,34.000000,89.504232,91.000000,64.000000
max,39.000000,99.967675,100.000000,77.000000

In [48]:
df.loc[0:5,'Study_Hours_per_Week']=None
df.loc[10:15,'Attendance_Rate']=None
df.loc[20:25,'Past_Exam_Scores']=None
df.loc[30:35, 'Finl_Exam_Score']=None

print("\nMissing values after inserting sample NANs")
print(df.isnull().sum()[df.isnull().sum() > 0])

Missing values after inserting sample NANs
Study_Hours_per_Week      6
Attendance_Rate           6
Past_Exam_Scores          6
Finl_Exam_Score         708
dtype: int64

In [49]:
df["Study_Hours_per_Week"].fillna(df["Study_Hours_per_Week"].mean())
df["Attendance_Rate"].fillna(df["Attendance_Rate"].median())

0      68.267841
1      78.222927
2      87.525096
3      92.076483
4      98.655517
         ...
703    84.658761
704    60.278990
705    98.384969
706    96.148012
707    80.404392
Name: Attendance_Rate, Length: 708, dtype: float64

In [50]:
df=pd.get_dummies(df,columns=["Parental_Education_Level"])
print("\nOne-Hot encoded columns")
print(df.columns.tolist())

One-Hot encoded columns
['Student_ID', 'Gender', 'Study_Hours_per_Week', 'Attendance_Rate', 'Past_Exam_Scores', 'Internet_Access_at_Home', 'Extracurricular_Activities', 'Final_Exam_Score', 'Pass_Fail', 'Finl_Exam_Score', 'Parental_Education_Level_Bachelors', 'Parental_Education_Level_High School', 'Parental_Education_Level_Masters', 'Parental_Education_Level_PhD']

In [51]:
le =LabelEncoder()
df["Pass_Fail_Encoded"] = le.fit_transform(df["Pass_Fail"])
print("\nLabel encoded column")
print(df.columns.tolist())

Label encoded column
['Student_ID', 'Gender', 'Study_Hours_per_Week', 'Attendance_Rate', 'Past_Exam_Scores', 'Internet_Access_at_Home', 'Extracurricular_Activities', 'Final_Exam_Score', 'Pass_Fail', 'Finl_Exam_Score', 'Parental_Education_Level_Bachelors', 'Parental_Education_Level_High School', 'Parental_Education_Level_Masters', 'Parental_Education_Level_PhD', 'Pass_Fail_Encoded']

In [52]:
df["Gender_Encoded"]=le.fit_transform(df["Gender"])
df["Internet_Access_Encoded"]=le.fit_transform(df["Internet_Access_at_Home"])
df["Extracurricular_Encoded"]=le.fit_transform(df["Extracurricular_Activities"])

In [53]:
df.to_csv("preprocessed_data.csv",index=False)
print("")